---
- src: geerlingguy.firewall
- src: geerlingguy.ntp
- src: geerlingguy.git
- src: geerlingguy.java
- src: geerlingguy.jenkins  #https://galaxy.ansible.com/geerlingguy/jenkins/ --> https://github.com/geerlingguy/ansible-role-jenkins
